name: Generate Rune Image

on:
  push:
    paths:
      - "counts.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Pillow
        run: pip install pillow

      - name: Generate Image
        run: python generate.py

      - name: Commit output
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add output.png
          git commit -m "Auto update rune image" || echo "No changes"
          git push
